language: android
dist: trusty
env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
    - extra
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
after_success:
  - bash <(curl -s https://codecov.io/bash) -t aaf7e8f7-d198-4ac1-9370-e8d4e5840497
